language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
      script:
        - cmake --build . --config Debug --parallel 3

    - name: "Sanitizer"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - sudo sysctl vm.mmap_rnd_bits=28 # https://stackoverflow.com/questions/77850769/fatal-threadsanitizer-unexpected-memory-mapping-when-running-on-linux-kernels 
        - mkdir build-address
        - pushd build-address
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Address ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-stack
        - pushd build-stack
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Stack ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-thread
        - pushd build-thread
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Thread ..
        - cmake --build . --config Debug --parallel 3
        - popd
      script:
        - pushd build-address/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-stack/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-thread/tests
        - ctest -j1 --output-on-failure

    - name: "Coverage"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      install:
        - sudo gem install coveralls-lcov
      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ..
      script:
        - cmake --build . --config Debug --parallel 3 --target coverage
      after_success:
        - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN --service-name travis-pro --service-job-id $TRAVIS_JOB_ID ./coverage.info

    - name: "GCC Unit Tests"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cd tests
        - ctest -j3 --output-on-failure

    - name: "Clang Unit Tests and Formatting"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cmake --build . --config Release --parallel 3 --target format.check
        - cd tests
        - ctest -j3 --output-on-failure

notifications:
  slack:
    secure: u4yTyHDPNvEEY5hWfQvVjYkmFfroQ3fOPn8T6ATzgP7DsO6Zl5pBGIdxQMNYAV3q+Qqg584J/xfRBt34MwBqVj+C+YpE146wTYsP6sRdcJtWaiMg6lDvZPMZZ9Rh053mwuHXKPcByxXuD6t9/atdJOIg0PCOdu0sq9L1Uuz/zv3ChOZe4B6ffqQjAbFx4Z++jki7XDpBYw9bqVha2d7tpsP/3PWsVdC+t15QfUp+NkMX1iPzBug0bofaHRgs7a2sBth2WrDWfK/p/FC8eM5dbBoyVuHhOiS7uBNi3411X5rtdk+uAw/Ftr4bwAFGJAOKC0/KMLu6mr5l8yOMl41gzqwjiiYYvfLQXYTEBVLAifACVnrsN3A0Fi9/PhgzaxAaThK2FqLdw1g4mBEySwQVt0/9iP/Mupl6QXE58Vfh9rnIPAnvnlF/68MhRJ3028IV8YcZLmSstchi+HJZgtRGprUO/dV6x8wuUKdzInTwkttqR1GWmL8js5OwY4nQzgoaPBcQI6t91kqJAxfw+tiTAVFhbuIqKPBFRA9mc+a7WgAynlgjZKa2otxYh3K6Q9ZaTtf3fQ1ws5uphozD0BW5rMrOFda42R+Bt7KgKSkxv7SBMs3MCRQ4E2elKYSdN4doH3nFYlSwg190avc+XOIJPquzMo3JlvdyZ/oxP2GggWU=
    on_success: never
